
POST http://localhost:4000/users HTTP/1.1
content-type: application/json

{
    "id": "58782365",
    "name": "bob"
}

###
GET http://localhost:4000/users

###
GET http://localhost:4000/users/123

###
GET http://localhost:4000/users/error

###
GET http://localhost:4000/users/unhandled-exception

###
GET http://localhost:4000/health

###
GET http://localhost:4000/
