POST http://localhost:4000/users HTTP/1.1
content-type: application/json

{
    "id": "1",
    "name": "bob"
}

###
GET http://localhost:4000/users

###
GET http://localhost:4000/users/123

###
GET http://localhost:4000/users/error

###
GET http://localhost:4000/users/error-unhandled

###
GET http://localhost:4000/users/error-uncaught

###
GET http://localhost:4000/users/wrapped-span-with-optional-name

###
GET http://localhost:4000/health
